name: labelGenerator
channels:
  - conda-forge
  - nodefaults
dependencies:
  - regex
  - loguru
  - pip
  - pip:
    - git+https://github.com/tschuelia/PyPythia.git@dev  # TODO: change to regular dependency once PyPythia 2.0 is released


