name: Setup IQ-TREE
runs:
  using: composite
  steps:
    - name: Download IQ-TREE MacOS
      if: runner.os == 'macOS'
      run: |
        wget https://github.com/iqtree/iqtree2/releases/download/v2.4.0/iqtree-2.4.0-macOS.zip
        unzip iqtree-*.zip && mv iqtree-*/* .
      shell: bash
    - name: Download IQ-TREE Linux
      if: runner.os == 'Linux'
      run: |
        wget https://github.com/iqtree/iqtree2/releases/download/v2.4.0/iqtree-2.4.0-Linux-intel.tar.gz
        tar xvf iqtree-*.tar.gz && mv iqtree-*/* .
      shell: bash
    - name: Unzip IQ-TREE and set Env variable
      run: echo iqtree2=$(pwd)/bin/iqtree2 >> $GITHUB_ENV
      shell: bash
    - name: Check IQ-TREE installation
      run: $iqtree2 -v
      shell: bash
