name: Test Label CLI
inputs:
  msa-file:
    description: MSA file to test Label CLI with
    default: examples/example.phy
runs:
  using: composite
  steps:
    - name: Run Label CLI with an exemplary MSA to make sure everything is working
      run: |
        label -m ${{ inputs.msa-file }} -r ${{ env.raxmlng }} -i ${{ env.iqtree2 }} --ntrees 4
      shell: bash -el {0}
